#!/bin/bash

TODAY=`date +%Y%m%d`
RAW="/Volumes/rawdata/MVDaily_$TODAY"
PROC="/Volumes/processed/MVDaily_$TODAY"
#RGB="/Volumes/processed/MVDaily_$TODAY/TIFF"
#FLAT="/Volumes/processed/MVDaily_$TODAY/Flat"

if [[ ! -z "$1" ]] ; then
BASE=$RAW/$1/Processed/$1
convert "$BASE"_008.tif "$BASE"_005.tif "$BASE"_003.tif -combine "Flat$TODAY.tif" 2>/dev/null
fi

while ((1)) ; do

LAST_SHOT=`ls -rt "$RAW" | tail -n 2 | head -n 1`

SUFF=${LAST_SHOT:$((${#LAST_SHOT}-2)):2}
if [[ "$SUFF" != "3D" ]] ; then
if [[ ! -f "$PROC/JPG/$LAST_SHOT.jpg" && -d "$RAW/$LAST_SHOT/Processed/" ]]
then
	echo "Next folio to process is $LAST_SHOT..."

	./composite_rgb.sh $LAST_SHOT
#	./develop_uv.sh $LAST_SHOT
	echo

fi
fi

sleep 15
done

